require 'java'
require 'red_storm'
require 'planet_hunters/json_scheme'

java_import 'storm.kafka.ZkHosts'
java_import 'storm.kafka.trident.OpaqueTridentKafkaSpout'
java_import 'storm.kafka.trident.TridentKafkaConfig'
java_import 'backtype.storm.spout.SchemeAsMultiScheme'

module PlanetHunters
  class KafkaClassificationsSpoutFactory

    def self.create(zk_host, project, client_id=nil)
      client_id ||= "storm-#{project}" 
      topic = "events_classifications_#{project}" # Reads from stream generated by zoo-storm topology

      brokers = ZkHosts.new(zk_host)

      conf = TridentKafkaConfig.new(brokers, topic, client_id)
      conf.scheme = SchemeAsMultiScheme.new(PlanetHunters::JsonScheme.new)

      OpaqueTridentKafkaSpout.new(conf)
    end

  end
end
